config/routes.rb
Rails.application.routes.draw do

  root 'whiskerfish#index'

  resources :missions, only: [:new, :create]

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  def self.total_word_count
    all_missions = self.all
    return 0 if all_missions == []
    word_counts = all_missions.map do |m|
      m.word_count
    end
    word_counts.reduce :+
  end

  def word_count
    #TODO:Is there a need for a better word count solution?
    return 0 if !self.body
    self.body.split.size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :pass_layout_vars

  protected
  
  def pass_layout_vars
    @missions = Mission.all 
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController 
  def new
    @mission = Mission.new
  end

  def create
    Mission.create!(mission_params)
    redirect_to root_path
  end

  private 

  def mission_params
    params[:mission].permit(:title, :body)
  end
  
end

app/controllers/whiskerfish_controller.rb
class WhiskerfishController < ApplicationController
  def index
    @missions = Mission.all
    @total_word_count = Mission.total_word_count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Whiskerfish" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Whiskerfish</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <%= render "/sidebar", :missions => @missions %>
         </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/missions/new.html.erb
<%= form_for @mission do |f| %>

Words Remaining: <span id="words-remaining">200</span>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit 'Save mission' %>
  <% end %>

app/views/whiskerfish/index.html.erb
Your daily mission statement

<p><%= link_to 'Add a mission', new_mission_path %></p>

<div id="whiskerfish">
  <% @missions.each do |mission| %>
    <p id="<%= mission.id %>"><%= mission.title %></p>
    <p><%= mission.body %></p>
  <% end %>
</div>

Total Word Count: <%= @total_word_count.to_s %>